apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo # this label is optional
spec:
  replicas: 1
  selector: # all the pods that match this label belongs to this deployment
    matchLabels:
      app: mongo 
  template: # for the pod
    metadata:
      labels:
        app: mongo # same label for pod instead of unique name, required
    spec:
      containers: # list of containers
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
--- # yaml syntax
apiVersion: v1
kind: Service # forwards request to pod
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 8080 #what we expose
      targetPort: 27017 # always be the same as the container port
