apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp # this label is optional
spec:
  replicas: 1
  selector: # all the pods that match this label belongs to this deployment
    matchLabels:
      app: webapp 
  template: # for the pod
    metadata:
      labels:
        app: webapp # same label for pod instead of unique name, required
    spec:
      containers: # list of containers
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password 
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url            
--- # yaml syntax
apiVersion: v1
kind: Service # forwards request to pod
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000 #what we expose
      targetPort: 3000 # always be the same as the container port
      nodePort: 30100

